### ISSUE TITLE
Publish vm-fdt to crates.io

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vm-fdt#8]
- [x] Update README.md (fill in or remove the existing TODOs)
- [x] Check if we need to update the public interface documentation
- [x] [Fix unchecked conversions from usize to u32](https://github.com/rust-vmm/vm-fdt/issues/7)
- [x] [Fix unchecked arithmetic conversions which might lead panics in debug mode](https://github.com/rust-vmm/vm-fdt/issues/6)
- [x] [Check that the memory reservations are valid](https://github.com/rust-vmm/vm-fdt/issues/5)
- [x] [Update interface to remove libfdt-related leftorver](https://github.com/rust-vmm/vm-fdt/issues/4)
- [x] https://github.com/rust-vmm/vm-fdt/issues/19

**Comment by lee128** [comment]
Glad to hear that news, when do you guys expect to finish the publish work? Can't wait to try this fdt interface instead of libfdt

**Comment by andreeaflorescu** [comment]
@lee128 we do not have a target date for publishing. We have to burn down through the open issues.

**Comment by andreeaflorescu** [comment]
@danielverkamp all the remaining issues are fixed, and I'd propose we publish the first version on crates.io. Are there any other things that you'd like us to do before?

**Comment by danielverkamp** [comment]
Everything looks OK to me.  What is the process for publishing to crates.io? Do we need to bump the version number?

**Comment by danielverkamp** [comment]
I made PR #29 to add a couple of Cargo.toml fields that seem to be required based on the docs at https://doc.rust-lang.org/cargo/reference/publishing.html

**Comment by andreeaflorescu** [comment]
The crate is now published: https://crates.io/crates/vm-fdt

@danielverkamp I invited you as a crate owner.
